services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    restart: unless-stopped
    command: node dist/index.js
    ports:
      - "8000:8000"
