services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    restart: unless-stopped
    command: node /rabit-backend/server.js
    ports:
      - "8000:8000"
    volumes:
      - "./RABIT-FRONTEND/uploads:/rabit-backend/uploads" # temporary: to be removed once db is used
