services:
  frontend:
    build: 
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    restart: unless-stopped
    ports: 
      - "8080:80"
  backend:
    build: 
      context: .
      dockerfile: ./docker/backend.Dockerfile
    restart: unless-stopped
    ports: 
      - "8000:80"
    volumes:
      - "./RABIT-FRONTEND/uploads:/var/www/rabit-backend/" # temporary: to be removed once db is used
