services:
  rabit:
    build: .
    command: node /rabit/backend/dist/index.js
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy # do not start RABIT until MySQL is ready
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: replace-this-with-something-super-secure
      DB_NAME: rabit
    volumes:
      - ./RABIT-BACKEND/.env:/rabit/.env
    ports: 
      - "8000:8000"
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rabit
      MYSQL_ROOT_PASSWORD: replace-this-with-something-super-secure
      MYSQL_USER: root
      MYSQL_PASSWORD: replace-this-with-something-super-secure
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./RABIT-BACKEND/database_schemas/DB_generation_schema.sql:/docker-entrypoint-initdb.d/DB_generation_schema.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  db-data: