name: Bug report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Before crearting an issue, make sure you read the [contributing guide](https://github.com/FIT3170-FY-Project-7/RABIT-COMMON/blob/main/CONTRIBUTING.md) and searched for similar issue.
  - type: markdown
    attributes:
      value: |
        If you have a general discussion or enquiry about RABIT and don't have an issue to report, please make a [discussion thread](https://github.com/FIT3170-FY-Project-7/RABIT-COMMON/discussions/new) instead.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
      - Windows
      - macOS
      - Linux
      - Android
      - iOS
      - Other
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: OS version
      description: Also include the OS name if you select 'Other' to the OS field.
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
        - Brave
        - Vivaldi
        - Opera
        - Other
    validations:
      required: true
  - type: input
    id: browser_version
    attributes:
      label: Browser version
      description: Also include the browser name if you select 'Other' to the browser field.
    validations:
      required: true
  - type: input
    id: device_model
    attributes:
      label: Device model
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
