name: Feature request
description: Suggest an idea for this project
title: "[Request] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Before crearting an issue, make sure you read the [contributing guide](https://fit3170-fy-project-7.github.io/RABIT-DOCS/dev-guide/contributing.html) and searched for similar issue.
  - type: markdown
    attributes:
      value: |
        If you have a general discussion or enquiry about RABIT and don't have an issue to report, please make a [discussion thread](https://github.com/FIT3170-FY-Project-7/RABIT-COMMON/discussions/new) instead.
  - type: textarea
    id: problem_related
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
